#!/bin/sh

exec podman run -it --rm \
    -v .:/home/dev/project:Z \
    -v ~/.claude:/tmp/claude-creds:ro,Z \
    -v ~/.cargo/registry:/usr/local/cargo/registry:Z \
    -e GIT_AUTHOR_NAME="Nigel Baillie" \
    -e GIT_COMMITTER_NAME="Nigel Baillie" \
    -e GIT_AUTHOR_EMAIL="nigel@baillie.dev" \
    -e GIT_COMMITTER_EMAIL="nigel@baillie.dev" \
    -w /home/dev/project \
    jail
