---
- name: install neovim and dependencies
  hosts: ubuntu
  become: yes
  become_user: root

  tasks:
    - name: install neovim
      apt:
        package: neovim
        state: latest
        update_cache: yes

    - name: set neovim as default editor
      alternatives:
        name: editor
        path: /usr/bin/nvim
        priority: 60

    - name: alias vim to neovim
      alternatives:
        name: vim
        path: /usr/bin/nvim
        priority: 60

    - name: neovim python dependencies
      apt: { package: "{{ item }}" }
      with_items:
        - python-dev
        - python-pip
        - python3-dev
        - python3-pip
      tags:
        - dependencies

# =================================================================

- name: install fzf
  hosts: ubuntu
  vars:
    home: "{{ ansible_env.HOME }}"
    sources_path: "{{ home }}/Sources"
  
  tasks:
    - name: clone fzf
      git:
        repo: https://github.com/junegunn/fzf.git
        dest: "{{ home }}/.fzf"
        depth: 1
      notify: install fzf
      tags:
        - fzf

  handlers:
    - name: install fzf
      command: "{{ home }}/.fzf/install --key-bindings --no-completion --update-rc"

# =================================================================

- name: install tmux
  hosts: ubuntu
  vars:
    home: "{{ ansible_env.HOME }}"

  tasks:
    - name: install tmux
      apt:
        package: tmux
        state: latest
        update_cache: yes
      tags:
        - tmux
