# Use global profile when available
if [ -f /usr/share/defaults/etc/profile ]; then
	. /usr/share/defaults/etc/profile
fi
# allow admin overrides
if [ -f /etc/profile ]; then
	. /etc/profile
fi


# vim-style input
set -o vi


# Copy/paste aliases
alias copy='xclip -sel clip -i'
alias paste='xclip -sel clip -o'


# Interesting R aliases from http://dwrodri.blog/posts/oct-7-Rscript-snippets.html
alias stats='Rscript -e "summary(as.numeric(readLines(\"stdin\")))"'   
alias boxplot='Rscript -e "boxplot(as.numeric(readLines(\"stdin\")))"'


# append to the history file, don't overwrite it
shopt -s histappend
# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000


# Homebrew
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)


# Make sure ~/bin is in $PATH
export PATH="$PATH:$HOME/bin"


# Nim
export PATH=/home/nigel/.nimble/bin:$PATH


# NVM for Node
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
